#!/usr/bin/env python

import os
import sys

sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'openshift'))

os.environ['DJANGO_SETTINGS_MODULE'] = 'openshift.settings'

virtenv = os.path.join(os.environ['OPENSHIFT_PYTHON_DIR'], 'virtenv')
os.environ['PYTHON_EGG_CACHE'] = os.path.join(
    virtenv, 'lib', 'python' + os.environ['OPENSHIFT_PYTHON_VERSION'], 'site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    exec(open(virtualenv).read(), dict(__file__=virtualenv))
except IOError:
    pass

import django.core.handlers.wsgi

application = django.core.handlers.wsgi.WSGIHandler()
